# Generated by Django 5.1.6 on 2025-02-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-created_at'], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='ava',
            field=models.ImageField(default='default.jpg', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='blogs', to='main.tagmodel'),
        ),
    ]
